# here, only test data with small file size can be downloaded.
# larger files for local testing are available on the MPCDF HPC clusters.
# In particular, this includes the following links for data sets in the testdata_path:
#  specObj-dr16.fits -> /virgotng/mpia/obs/SDSS/specObj-dr16.fits
#  TNG100-3_snapshot -> /virgotng/universe/IllustrisTNG/TNG100-3/output/snapdir_099
#  TNG100-2_snapshot -> /virgotng/universe/IllustrisTNG/TNG100-2/output/snapdir_099
#  TNG100-2_group -> /virgotng/universe/IllustrisTNG/TNG100-2/output/groups_099
#  TNG100-3_group -> /virgotng/universe/IllustrisTNG/TNG100-3/output/groups_099
#  TNG100_group -> /virgotng/universe/IllustrisTNG/TNG100-1/output/groups_099
#  TNG100_snapshot -> /virgotng/universe/IllustrisTNG/TNG100-1/output/snapdir_099
#  MTNGarepo_270hydro_snapshot_z10 -> /virgotng/mpa/MTNG/Hydro-Arepo/MTNG-L62.5-540-A/output/snapdir_031
#  MTNGarepo_270hydro_group_z10 -> /virgotng/mpa/MTNG/Hydro-Arepo/MTNG-L62.5-540-A/output/groups_031
#  MTNGarepo_270hydro_group_z2 -> /virgotng/mpa/MTNG/Hydro-Arepo/MTNG-L62.5-540-A/output/groups_129
#  MTNGarepo_270hydro_snapshot_z2 -> /virgotng/mpa/MTNG/Hydro-Arepo/MTNG-L62.5-540-A/output/snapdir_129
#  EAGLE -> /virgotng/universe/Eagle/RecalL0025N0752
#  Millenium_snapshot -> /virgotng/universe/Millennium-1/output/snapdir_063/snap_063.hdf5
#  TNG300_group -> /virgotng/universe/IllustrisTNG/TNG300-1/output/groups_099
#  TNG300_snapshot -> /virgotng/universe/IllustrisTNG/TNG300-1/output/snapdir_099
#  TNG50_snapshot -> /virgotng/universe/IllustrisTNG/TNG50-1/output/snapdir_099
#  TNG50_group -> /virgotng/universe/IllustrisTNG/TNG50-1/output/groups_099
#  TNG50-4_group -> /virgotng/universe/IllustrisTNG/TNG50-4/output/groups_099
#  TNG50-4_snapshot -> /virgotng/universe/IllustrisTNG/TNG50-4/output/snapdir_099
#  TNG50 -> /virgotng/universe/IllustrisTNG/TNG50-1
#  TNGcluster -> /virgotng/mpia/TNG-Cluster/L680n8192TNG


name: 'get-testdata'
description: 'download test data'
inputs:
  outputfolder:
    description: 'folder to download to'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_FIRE2_snapshot_z1.hdf5
        url: https://heibox.uni-heidelberg.de/f/856c4ffbcc644530a27d/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG50-4_snapshot_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/53ac454aa304481bb32e/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG50-1_snapshot_z3.hdf5
        url: https://heibox.uni-heidelberg.de/f/58b9fbdc6a3043119b5c/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG50-1_snapshot_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/638ae4b2a1514adeb654/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG50-1_group_z3.hdf5
        url: https://heibox.uni-heidelberg.de/f/8a1c26b2140e4e2bb06c/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG50-1_group_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/1a7eb3e0b7f243038b13/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_FIRE2_simulation.tar.gz
        url: https://heibox.uni-heidelberg.de/f/99a6c5fe31eb430f90e2/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG-Cluster_snapshot_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/fe582fbe745445d7a448/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_LGal21_z3.hdf5
        url: https://heibox.uni-heidelberg.de/f/6a24e9db7b8a449d94be/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG100-3_snapshot_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/6eb403619c534e52bb82/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG100-3_group_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/699142c6855341d1bb34/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG100-2_snapshot_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/e3c9c3f591574b969557/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG100-2_group_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/ed8a1b34a9fe40b1b493/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_flamingo_snapshot.hdf5
        url: https://heibox.uni-heidelberg.de/f/8749a46fdfc74577b29a/?dl=1
