name: 'get-testdata'
description: 'download test data'
inputs:
  outputfolder:
    description: 'folder to download to'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_FIRE2_snapshot_z1.hdf5
        url: https://heibox.uni-heidelberg.de/f/856c4ffbcc644530a27d/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG50-4_snapshot_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/53ac454aa304481bb32e/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG50-1_snapshot_z3.hdf5
        url: https://heibox.uni-heidelberg.de/f/58b9fbdc6a3043119b5c/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG50-1_snapshot_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/638ae4b2a1514adeb654/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG50-1_group_z3.hdf5
        url: https://heibox.uni-heidelberg.de/f/8a1c26b2140e4e2bb06c/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG50-1_group_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/1a7eb3e0b7f243038b13/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_FIRE2_simulation.tar.gz
        url: https://heibox.uni-heidelberg.de/f/99a6c5fe31eb430f90e2/?dl=1
    - uses: ./.github/actions/get-testdata
      with:
        outputfolder: ${{ inputs.outputfolder }}
        filename: minimal_TNG-Cluster_snapshot_z0.hdf5
        url: https://heibox.uni-heidelberg.de/f/fe582fbe745445d7a448/?dl=1
